apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: grpc-client
    spec:
      containers:
      - image: ritazh/tracee-grpc-client
        imagePullPolicy: Always
        name: grpc-client
      restartPolicy: Always