apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: grpc-service
    spec:
      containers:
      - image: ritazh/tracee-grpc-server
        imagePullPolicy: Always
        name: grpc-service
        ports:
        - containerPort: 10000
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    run: grpc-service
  sessionAffinity: None
  clusterIP: None #type: LoadBalancer
